phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      # Install AWS CLI
      - apt-get update
      - apt-get install -y awscli
      - export JAVA_HOME=$(/usr/libexec/java_home)
      - export PATH=$JAVA_HOME/jre/bin:$PATH
  build:
    commands:
        - echo "Starting batch pipeline..."
        - echo "Executing Command 1..."
        - cd note-app-serverless/aws-serverless-note-app && ./mvnw -DskipTests clean package
        - echo "Success Command 1..."
        - echo "Start Command 2..."
        - aws s3 cp note-app-serverless/aws-serverless-note-app/target/aws-serverless-note-app-0.0.1-SNAPSHOT.jar s3://cf-templates-1ohbdpx0bstp8-us-east-1/aws-serverless-note-app-0.0.1-SNAPSHOT.jar
        - echo "Success Command 2..."
        - echo "Start Command 3..."
        - export S3_URL=$(aws s3 presign s3://cf-templates-1ohbdpx0bstp8-us-east-1/aws-serverless-note-app-0.0.1-SNAPSHOT.jar --expires-in 3600)
        - echo "Success Command 3..."
        - echo "Start Command 4..."
        - aws lambda update-function-code --function-name LambdaAddDataFunction --s3-bucket cf-templates-1ohbdpx0bstp8-us-east-1 --s3-key aws-serverless-note-app-0.0.1-SNAPSHOT.jar
        - aws lambda update-function-code --function-name LambdaDeleteNote --s3-bucket cf-templates-1ohbdpx0bstp8-us-east-1 --s3-key aws-serverless-note-app-0.0.1-SNAPSHOT.jar
        - aws lambda update-function-code --function-name LambdaFetchDataFunction --s3-bucket cf-templates-1ohbdpx0bstp8-us-east-1 --s3-key aws-serverless-note-app-0.0.1-SNAPSHOT.jar 
        - echo "End..."
  artifacts:
    files: ['note-app-serverless/aws-serverless-note-app/target/aws-serverless-note-app-0.0.1-SNAPSHOT.jar']