version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
      maven: 3.9.6
    # commands:
    #   - export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
    #   - export PATH=$JAVA_HOME/bin:$PATH
  build:
    commands:
      - ls
      - cd note-app-serverless/aws-serverless-note-app
      - ls -lrt
      - mvn clean package -DskipTests=true
