version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
      maven: 3.9.6
    # commands:
    #   - export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
    #   - export PATH=$JAVA_HOME/bin:$PATH
  build:
    commands:
      - ls
      - cd note-app-serverless/aws-serverless-note-app
      - ls -lrt
      - mvn clean package -DskipTests=true
  post_build:
    commands:
      # Upload JAR file to S3
      - aws s3 cp note-app-serverless/aws-serverless-note-app/target/aws-serverless-note-app-0.0.1-SNAPSHOT.jar s3://cf-templates-1ohbdpx0bstp8-us-east-1/aws-serverless-note-app-0.0.1-SNAPSHOT.jar
      
      # Get public URL of the uploaded JAR file
      - export S3_URL=$(aws s3 presign s3://cf-templates-1ohbdpx0bstp8-us-east-1/aws-serverless-note-app-0.0.1-SNAPSHOT.jar --expires-in 3600)
      
      # Display the public URL
      - echo "Public URL of the JAR file: $S3_URL"
      # Update force lambda function
      - aws lambda update-function-code --function-name LambdaAddDataFunction --s3-bucket cf-templates-1ohbdpx0bstp8-us-east-1 --s3-key aws-serverless-note-app-0.0.1-SNAPSHOT.jar
      - aws lambda update-function-code --function-name LambdaDeleteNote --s3-bucket cf-templates-1ohbdpx0bstp8-us-east-1 --s3-key aws-serverless-note-app-0.0.1-SNAPSHOT.jar
      - aws lambda update-function-code --function-name LambdaFetchDataFunction --s3-bucket cf-templates-1ohbdpx0bstp8-us-east-1 --s3-key aws-serverless-note-app-0.0.1-SNAPSHOT.jar 
    